import "@/styles/globals.css";

import { type Metadata } from "next";
import { Inter } from "next/font/google";
import { TooltipProvider } from "@radix-ui/react-tooltip"

export const metadata: Metadata = {
  title: "Blue Bank",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TooltipProvider delayDuration={0}>
          {children}
        </TooltipProvider>
      </body>
    </html>
  );
}
